---


- hosts: runners
  user: ubuntu
  become: yes
  vars_files:
      - vars/gitlab_master.yml
  roles:
    - docker


- hosts: masters
  user: ubuntu
  become: yes
  vars_files:
      - vars/gitlab_master.yml
  roles:
    - role: pip